// ===== ملف الترجمات =====
const translations = {
    ar: {
        appTitle: 'إدارة المصاريف',
        welcome: 'مرحباً',
        logout: 'خروج',
        totalIncome: 'إجمالي الدخل',
        totalExpenses: 'إجمالي المصروفات',
        remaining: 'المتبقي',
        monthlyBudget: 'الميزانية الشهرية',
        clickToEdit: '(اضغط للتعديل)',
        transactionCount: 'عدد المعاملات',
        expenseDistribution: 'توزيع المصروفات حسب الفئة',
        expenseTrend: 'اتجاه المصروفات (آخر 7 أيام)',
        addTransaction: 'إضافة معاملة جديدة',
        description: 'الوصف',
        amount: 'المبلغ',
        category: 'الفئة',
        type: 'النوع',
        expense: 'مصروف',
        income: 'دخل',
        add: 'إضافة',
        manageCategories: 'إدارة الفئات',
        newCategoryName: 'اسم الفئة الجديدة',
        icon: 'رمز تعبيري',
        color: 'اللون',
        addCategory: 'إضافة فئة',
        allTransactions: 'جميع المعاملات',
        search: 'بحث...',
        allCategories: 'جميع الفئات',
        allTypes: 'الكل',
        exportCSV: 'تصدير CSV',
        actions: 'الإجراءات',
        noTransactions: 'لا توجد معاملات',
        login: 'تسجيل الدخول',
        register: 'إنشاء حساب جديد',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        name: 'الاسم الكامل',
        dontHaveAccount: 'ليس لديك حساب؟',
        haveAccount: 'لديك حساب؟',
        registerNow: 'سجل الآن',
        loginNow: 'تسجيل الدخول',
        deleteConfirm: 'هل أنت متأكد من الحذف؟',
        default: 'افتراضي',
        edit: 'تعديل',
        delete: 'حذف',
        selectCategory: 'اختر الفئة',
        noCategories: 'لا توجد فئات مخصصة',
        fillAllFields: 'يرجى ملء جميع الحقول',
        serverError: 'خطأ في الاتصال بالخادم',
        enterCategoryName: 'يرجى إدخال اسم الفئة',
        editCategoryName: 'تعديل اسم الفئة',
        editIcon: 'تعديل الرمز التعبيري',
        editColor: 'تعديل اللون (رمز سداسي)',
        dailyExpenses: 'المصروفات اليومية',
        noDataToExport: 'لا توجد معاملات للتصدير',
       settings: 'الإعدادات',
        savingGoals: 'أهداف الادخار',
    loginRequired: 'يرجى تسجيل الدخول لعرض التحليلات',
sessionExpired: 'انتهت صلاحية الجلسة. جاري إعادة التوجيه...',
loadingAnalytics: '⏳ جاري تحميل التحليلات...',
analyticsError: 'حدث خطأ أثناء تحميل التحليلات',
analyticsConnectionError: 'حدث خطأ في الاتصال بالخادم',
noAnalyticsData: 'لا توجد بيانات تحليلية متاحة',
noInsights: 'لا توجد توصيات حالياً',
'trend.up': 'صاعد 📈',
'trend.down': 'هابط 📉',
'trend.stable': 'متذبذب',
'strength.strong': 'قوية',
'strength.medium': 'متوسطة',
'strength.weak': 'ضعيفة',
'correlationType.positive': 'طردية (زيادة مع زيادة)',
'correlationType.negative': 'عكسية (زيادة مع نقصان)',
'correlationType.unknown': 'غير معروف',
'anomalyReason.high': 'أعلى من المعتاد (Outlier)',
'anomalyReason.low': 'أقل من المعتاد (Outlier)',
'anomalyReason.zscore': 'تباين كبير (Z-Score)',
'spendingType.إنفاق مرتفع': 'إنفاق مرتفع',
'spendingType.إنفاق متوسط': 'إنفاق متوسط',
'spendingType.إنفاق منخفض': 'إنفاق منخفض',
'prediction.title': 'توقع المصروفات للشهر القادم',
'prediction.confidence': 'دقة:',
'prediction.trend': 'الاتجاه:',
'anomalies.title': 'المعاملات غير الطبيعية',
'anomalies.unknown': 'معاملة غير معروفة',
'anomalies.unknownReason': 'غير محدد',
'correlations.title': 'العلاقات بين الفئات',
'summary.title': 'ملخص سريع',
'summary.totalExpenses': 'المصروفات الكلية',
'summary.totalIncome': 'الدخل الكلي',
'summary.transactionCount': 'عدد المعاملات',
'summary.expenseCount': 'عدد معاملات المصروف',
'summary.averageExpense': 'متوسط الإنفاق لكل معاملة مصروف',
'insight.budget_exceed_forecast.title': '⚠️ تحذير: توقع تجاوز الميزانية',
'insight.budget_exceed_forecast.desc': 'من المتوقع أن تنفق {projected} DZD الشهر القادم، وهو ما يتجاوز ميزانيتك الشهرية ({budget} DZD) بنسبة {percent}%',
'insight.budget_exceed_forecast.action': 'فكر في تقليل النفقات غير الضرورية',
'insight.budget_forecast.title': '📊 توقع المصروفات الشهرية',
'insight.budget_forecast.desc': 'من المتوقع أن تنفق {projected} DZD الشهر القادم، ضمن ميزانيتك الشهرية ({budget} DZD)',
'insight.budget_forecast.action': 'استمر في الإنفاق الحكيم',
'insight.correlation_found.title': '🔗 علاقة بين الفئات',
'insight.correlation_found.desc': 'هناك علاقة {strength} {type} بين "{cat1}" و "{cat2}" (معامل الارتباط: {corr})',
'insight.correlation_found.action': 'حاول مراقبة هاتين الفئتين معاً للتحكم في الإنفاق',
'insight.anomaly_detected.title': '🚨 نفقة غير معتادة',
'insight.anomaly_detected.desc': 'تم اكتشاف معاملة غير عادية: "{desc}" بقيمة {amount} DZD ({reason})',
'insight.anomaly_detected.action': 'تأكد من صحة هذه المعاملة',
'insight.goal_progress.title': '🎯 تقدم هدف الادخار',
'insight.goal_progress.desc': '{name}: تم تحقيق {progress}% من الهدف ({remaining} DZD متبقية)',
'insight.goal_progress.action': 'أنت على وشك تحقيق هدفك! استمر',
'insight.spending_behavior.title': '📈 نمط الإنفاق',
'insight.spending_behavior.desc': 'معظم إنفاقك ({count} معاملة) هو {type} بمتوسط {avg} DZD، وأغلبها في "{category}"',
'insight.spending_behavior.action': 'يمكنك مراجعة هذه المعاملات للبحث عن فرص للتوفير',
'insight.saving_suggestion.title': '💡 اقتراح توفير',
'insight.saving_suggestion.desc': 'فئة "{category}" تشكل {percent}% من إجمالي مصروفاتك ({amount} DZD)',
'insight.saving_suggestion.action': 'حاول تقليل الإنفاق على "{category}" بنسبة 10% لتوفير {savings} DZD شهرياً',
  addGoal: 'إضافة هدف',
newGoal: 'هدف جديد',
goalName: 'اسم الهدف',
targetAmount: 'المبلغ المستهدف',
deadline: 'تاريخ الانتهاء',
goalIcon: 'رمز تعبيري (🎯)',
addAmount: 'إضافة مبلغ',
enterAmount: 'أدخل المبلغ المراد إضافته:',
enterValidAmount: 'يرجى إدخال مبلغ صحيح',
goalAchieved: '🎉 تهانينا! لقد حققت هدفك!',
goalCreated: 'تم إنشاء الهدف بنجاح',
noGoals: 'لا توجد أهداف',
daysLeft: 'يوم متبقي',
deadlinePassed: 'انتهى الموعد',
save: 'حفظ',
preferredCurrency: 'العملة المفضلة',
emailNotifications: 'تفعيل الإشعارات البريدية عند تجاوز الميزانية',
notificationEmail: 'بريد الإشعارات (اختياري)',
saveSettings: 'حفظ الإعدادات',
settingsUpdated: '✅ تم تحديث الإعدادات بنجاح',
analytics: 'تحليلات ذكية',
loadingAnalytics: 'جاري تحميل التحليلات...',
        topCategory: 'أعلى فئة إنفاق',
dailyAverage: 'متوسط الإنفاق اليومي',
thisMonth: 'هذا الشهر',
savingsRate: 'نسبة الادخار',
daysLeft: 'الأيام المتبقية',
untilMonthEnd: 'حتى نهاية الشهر',
vsLastMonth: 'مقارنة بالشهر الماضي',
moreThanLastMonth: 'أكثر من الشهر الماضي',
lessThanLastMonth: 'أقل من الشهر الماضي',
sameAsLastMonth: 'مثل الشهر الماضي',
fastestGoal: 'أسرع هدف ادخار',
noGoals: 'لا توجد أهداف',
        date: 'التاريخ',
        budgetProgress: 'الميزانية الشهرية',
budgetStatusSafe: '✅ ضمن الميزانية',
budgetStatusWarning: '⚠️ اقتربت من الحد الأقصى',
budgetStatusDanger: '🚨 تجاوزت الميزانية!',
     overBudgetAlert: '⚠️ تحذير: لقد تجاوزت ميزانيتك الشهرية بمبلغ {amount} !',
     overBudgetToast: '⚠️ تحذير: بعد إضافة هذه المعاملة، تجاوزت ميزانيتك الشهرية ({budget}) بمبلغ {amount}',
     budgetWarning: '⚠️ تنبيه: المتبقي من ميزانيتك الشهرية هو {amount} فقط.',
        budgetUpdated: '✅ تم تحديث الميزانية الشهرية بنجاح!',
        enterValidNumber: 'الرجاء إدخال رقم موجب صحيح',
        defaultCategories: {
            Food: 'طعام',
            Transport: 'مواصلات',
            Books: 'كتب',
            Supplies: 'مستلزمات',
            Entertainment: 'ترفيه',
            Rent: 'إيجار',
            Utilities: 'فواتير',
            Healthcare: 'صحة',
            Other: 'أخرى'
        }
    },
    fr: {
        appTitle: 'Gestionnaire de dépenses',
        welcome: 'Bienvenue',
        logout: 'Déconnexion',
        totalIncome: 'Revenu total',
        totalExpenses: 'Dépenses totales',
        remaining: 'Reste',
        monthlyBudget: 'Budget mensuel',
        clickToEdit: '(Cliquez pour modifier)',
        transactionCount: 'Nombre de transactions',
        expenseDistribution: 'Répartition des dépenses par catégorie',
        expenseTrend: 'Tendance des dépenses (7 derniers jours)',
        addTransaction: 'Ajouter une transaction',
        description: 'Description',
        amount: 'Montant',
        category: 'Catégorie',
        type: 'Type',
        expense: 'Dépense',
        income: 'Revenu',
        add: 'Ajouter',
        manageCategories: 'Gérer les catégories',
        newCategoryName: 'Nom de la nouvelle catégorie',
        icon: 'Emoji',
        color: 'Couleur',
        addCategory: 'Ajouter une catégorie',
        allTransactions: 'Toutes les transactions',
        search: 'Rechercher...',
        allCategories: 'Toutes les catégories',
        allTypes: 'Tous',
        exportCSV: 'Exporter CSV',
        actions: 'Actions',
        noTransactions: 'Aucune transaction',
        login: 'Connexion',
        register: 'Créer un compte',
        email: 'Email',
        password: 'Mot de passe',
        name: 'Nom complet',
        dontHaveAccount: "Vous n'avez pas de compte ?",
        haveAccount: 'Vous avez déjà un compte ?',
        registerNow: "Inscrivez-vous",
        loginNow: 'Connectez-vous',
        deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ?',
        default: 'Défaut',
        edit: 'Modifier',
        delete: 'Supprimer',
        selectCategory: 'Choisir une catégorie',
        noCategories: 'Aucune catégorie personnalisée',
        fillAllFields: 'Veuillez remplir tous les champs',
        serverError: 'Erreur de connexion au serveur',
        enterCategoryName: 'Veuillez saisir un nom de catégorie',
        editCategoryName: 'Modifier le nom de la catégorie',
        editIcon: "Modifier l'icône",
        editColor: 'Modifier la couleur (code hexadécimal)',
        dailyExpenses: 'Dépenses quotidiennes',
        noDataToExport: 'Aucune transaction à exporter',
        settings: 'Paramètres',
        savingGoals: 'Objectifs d\'épargne',
loginRequired: 'Veuillez vous connecter pour voir les analyses',
sessionExpired: 'Session expirée. Redirection...',
loadingAnalytics: 'Chargement des analyses...',
analyticsError: 'Erreur lors du chargement des analyses',
noAnalyticsData: 'Aucune donnée d\'analyse disponible',
insight: 'Aperçu',
noDetails: 'Aucun détail disponible',
noAction: 'Aucune action suggérée',
noInsights: 'Aucun aperçu disponible',
nextMonthPrediction: 'Prévision des dépenses du mois prochain',
accuracy: 'Précision',
trend: 'Tendance',
trendIncreasing: 'À la hausse',
trendDecreasing: 'À la baisse',
trendStable: 'Stable',
anomalies: 'Anomalies',
unknownTransaction: 'Transaction inconnue',
unspecified: 'Non spécifié',
correlations: 'Corrélations entre catégories',
weak: 'Faible',
unknown: 'Inconnu',
quickSummary: 'Résumé rapide',
totalExpensesLabel: 'Dépenses totales',
totalIncomeLabel: 'Revenu total',
transactionCountLabel: 'Nombre de transactions',
expenseCountLabel: 'Nombre de transactions de dépenses',
averageExpenseLabel: 'Dépense moyenne par transaction',
addGoal: 'Ajouter un objectif',
newGoal: 'Nouvel objectif',
goalName: 'Nom de l\'objectif',
targetAmount: 'Montant cible',
deadline: 'Date limite',
goalIcon: 'Emoji (🎯)',
addAmount: 'Ajouter un montant',
enterAmount: 'Entrez le montant à ajouter :',
enterValidAmount: 'Veuillez entrer un montant valide',
goalAchieved: '🎉 Félicitations ! Vous avez atteint votre objectif !',
goalCreated: 'Objectif créé avec succès',
noGoals: 'Aucun objectif',
daysLeft: 'jours restants',
deadlinePassed: 'Délai dépassé',
save: 'Enregistrer',
preferredCurrency: 'Devise préférée',
emailNotifications: 'Activer les notifications par e-mail en cas de dépassement du budget',
notificationEmail: 'E-mail de notification (facultatif)',
saveSettings: 'Enregistrer les paramètres',
settingsUpdated: '✅ Paramètres mis à jour avec succès',
        budgetProgress: 'Budget mensuel',
budgetStatusSafe: '✅ Dans le budget',
budgetStatusWarning: '⚠️ Approche de la limite',
budgetStatusDanger: '🚨 Budget dépassé !',
analytics: 'AI Analytics',
loadingAnalytics: 'Loading analytics...',
        topCategory: 'Catégorie de dépense la plus élevée',
dailyAverage: 'Dépense quotidienne moyenne',
thisMonth: 'Ce mois-ci',
savingsRate: "Taux d'épargne",
daysLeft: 'Jours restants',
untilMonthEnd: "Jusqu'à la fin du mois",
vsLastMonth: 'Comparaison avec le mois dernier',
moreThanLastMonth: 'Plus que le mois dernier',
lessThanLastMonth: 'Moins que le mois dernier',
sameAsLastMonth: 'Comme le mois dernier',
fastestGoal: 'Objectif le plus proche',
noGoals: 'Aucun objectif',   
loadingAnalytics: '⏳ Chargement des analyses...',
analyticsError: 'Une erreur est survenue lors du chargement des analyses',
analyticsConnectionError: 'Erreur de connexion au serveur',
noAnalyticsData: 'Aucune donnée d\'analyse disponible',
noInsights: 'Aucune recommandation pour le moment',
'trend.up': 'Hausse 📈',
'trend.down': 'Baisse 📉',
'trend.stable': 'Stable',
'strength.strong': 'Forte',
'strength.medium': 'Moyenne',
'strength.weak': 'Faible',
'correlationType.positive': 'Positive (augmentation ensemble)',
'correlationType.negative': 'Négative (augmentation/diminution)',
'correlationType.unknown': 'Inconnue',
'anomalyReason.high': 'Supérieur à la normale (Valeur aberrante)',
'anomalyReason.low': 'Inférieur à la normale (Valeur aberrante)',
'anomalyReason.zscore': 'Écart important (Z-Score)',
'spendingType.إنفاق مرتفع': 'Dépenses élevées',
'spendingType.إنفاق متوسط': 'Dépenses moyennes',
'spendingType.إنفاق منخفض': 'Dépenses faibles',
'prediction.title': 'Prévision des dépenses pour le mois prochain',
'prediction.confidence': 'Précision :',
'prediction.trend': 'Tendance :',
'anomalies.title': 'Transactions anormales',
'anomalies.unknown': 'Transaction inconnue',
'anomalies.unknownReason': 'Non spécifié',
'correlations.title': 'Relations entre les catégories',
'summary.title': 'Résumé rapide',
'summary.totalExpenses': 'Dépenses totales',
'summary.totalIncome': 'Revenu total',
'summary.transactionCount': 'Nombre de transactions',
'summary.expenseCount': 'Nombre de transactions de dépenses',
'summary.averageExpense': 'Dépense moyenne par transaction',
'insight.budget_exceed_forecast.title': '⚠️ Alerte : dépassement de budget prévu',
'insight.budget_exceed_forecast.desc': 'Vous devriez dépenser {projected} DZD le mois prochain, ce qui dépasse votre budget mensuel ({budget} DZD) de {percent}%',
'insight.budget_exceed_forecast.action': 'Réduisez les dépenses inutiles',
'insight.budget_forecast.title': '📊 Prévision des dépenses mensuelles',
'insight.budget_forecast.desc': 'Vous devriez dépenser {projected} DZD le mois prochain, dans votre budget mensuel ({budget} DZD)',
'insight.budget_forecast.action': 'Continuez à dépenser judicieusement',
'insight.correlation_found.title': '🔗 Relation entre les catégories',
'insight.correlation_found.desc': 'Il existe une relation {strength} {type} entre "{cat1}" et "{cat2}" (coefficient de corrélation : {corr})',
'insight.correlation_found.action': 'Surveillez ces deux catégories ensemble',
'insight.anomaly_detected.title': '🚨 Dépense inhabituelle',
'insight.anomaly_detected.desc': 'Une transaction inhabituelle a été détectée : "{desc}" pour un montant de {amount} DZD ({reason})',
'insight.anomaly_detected.action': 'Vérifiez cette transaction',
'insight.goal_progress.title': '🎯 Progression de l\'objectif d\'épargne',
'insight.goal_progress.desc': '{name} : atteint {progress}% de l\'objectif ({remaining} DZD restants)',
'insight.goal_progress.action': 'Vous êtes sur le point d\'atteindre votre objectif ! Continuez',
'insight.spending_behavior.title': '📈 Modèle de dépenses',
'insight.spending_behavior.desc': 'La plupart de vos dépenses ({count} transactions) sont {type} avec une moyenne de {avg} DZD, principalement dans "{category}"',
'insight.spending_behavior.action': 'Examinez ces transactions pour trouver des opportunités d\'économies',
'insight.saving_suggestion.title': '💡 Suggestion d\'économie',
'insight.saving_suggestion.desc': 'La catégorie "{category}" représente {percent}% de vos dépenses totales ({amount} DZD)',
'insight.saving_suggestion.action': 'Essayez de réduire les dépenses sur "{category}" de 10% pour économiser {savings} DZD par mois',
        date: 'Date',
        overBudgetAlert: '⚠️ Attention : vous avez dépassé votre budget mensuel de {amount} !',
        overBudgetToast: '⚠️ Attention : après cette transaction, vous avez dépassé votre budget mensuel ({budget}) de {amount}',
        budgetWarning: '⚠️ Attention : il ne vous reste que {amount} de votre budget mensuel.',
        budgetUpdated: '✅ Budget mensuel mis à jour avec succès !',
        enterValidNumber: 'Veuillez entrer un nombre valide (>= 0)',
        defaultCategories: {
            Food: 'Nourriture',
            Transport: 'Transport',
            Books: 'Livres',
            Supplies: 'Fournitures',
            Entertainment: 'Divertissement',
            Rent: 'Loyer',
            Utilities: 'Factures',
            Healthcare: 'Santé',
            Other: 'Autre'
        }
    },
    en: {
        appTitle: 'Expenses Manager',
        welcome: 'Welcome',
        logout: 'Logout',
        totalIncome: 'Total Income',
        totalExpenses: 'Total Expenses',
        remaining: 'Remaining',
        monthlyBudget: 'Monthly Budget',
        clickToEdit: '(Click to edit)',
        transactionCount: 'Transactions Count',
        expenseDistribution: 'Expense Distribution by Category',
        expenseTrend: 'Expense Trend (Last 7 Days)',
        addTransaction: 'Add Transaction',
        description: 'Description',
        amount: 'Amount',
        category: 'Category',
        type: 'Type',
        expense: 'Expense',
        income: 'Income',
        add: 'Add',
        manageCategories: 'Manage Categories',
        newCategoryName: 'New Category Name',
        icon: 'Emoji',
        color: 'Color',
        addCategory: 'Add Category',
        allTransactions: 'All Transactions',
        search: 'Search...',
        allCategories: 'All Categories',
        allTypes: 'All',
        exportCSV: 'Export CSV',
        actions: 'Actions',
        noTransactions: 'No transactions',
        login: 'Login',
        register: 'Create Account',
        email: 'Email',
        password: 'Password',
        name: 'Full Name',
        dontHaveAccount: "Don't have an account?",
        haveAccount: 'Already have an account?',
        registerNow: 'Register Now',
        loginNow: 'Login Now',
        deleteConfirm: 'Are you sure you want to delete?',
        default: 'Default',
        edit: 'Edit',
        delete: 'Delete',
        selectCategory: 'Select Category',
        noCategories: 'No custom categories',
        fillAllFields: 'Please fill all fields',
        serverError: 'Server connection error',
        enterCategoryName: 'Please enter a category name',
        editCategoryName: 'Edit category name',
        editIcon: 'Edit emoji',
        editColor: 'Edit color (hex code)',
        dailyExpenses: 'Daily Expenses',
        noDataToExport: 'No transactions to export',
        settings: 'Settings',
        savingGoals: 'Saving Goals',
    loginRequired: 'Please login to view analytics',
sessionExpired: 'Session expired. Redirecting...',
addGoal: 'Add Goal',
newGoal: 'New Goal',
goalName: 'Goal Name',
targetAmount: 'Target Amount',
deadline: 'Deadline',
goalIcon: 'Emoji (🎯)',
addAmount: 'Add Amount',
enterAmount: 'Enter the amount to add:',
enterValidAmount: 'Please enter a valid amount',
goalAchieved: '🎉 Congratulations! You achieved your goal!',
goalCreated: 'Goal created successfully',
noGoals: 'No goals yet',
daysLeft: 'days left',
deadlinePassed: 'Deadline passed',
save: 'Save',
preferredCurrency: 'Preferred Currency',
emailNotifications: 'Enable email notifications when over budget',
notificationEmail: 'Notification Email (optional)',
saveSettings: 'Save Settings',
settingsUpdated: '✅ Settings updated successfully',
loadingAnalytics: '⏳ Loading analytics...',
analyticsError: 'Error loading analytics',
analyticsConnectionError: 'Server connection error',
noAnalyticsData: 'No analytics data available',
noInsights: 'No insights available',
'trend.up': 'Up 📈',
'trend.down': 'Down 📉',
'trend.stable': 'Stable',
'strength.strong': 'Strong',
'strength.medium': 'Medium',
'strength.weak': 'Weak',
'correlationType.positive': 'Positive (increase together)',
'correlationType.negative': 'Negative (increase/decrease)',
'correlationType.unknown': 'Unknown',
'anomalyReason.high': 'Above normal (Outlier)',
'anomalyReason.low': 'Below normal (Outlier)',
'anomalyReason.zscore': 'Large deviation (Z-Score)',
'spendingType.إنفاق مرتفع': 'High Spending',
'spendingType.إنفاق متوسط': 'Medium Spending',
'spendingType.إنفاق منخفض': 'Low Spending',
'prediction.title': 'Expense Forecast for Next Month',
'prediction.confidence': 'Confidence:',
'prediction.trend': 'Trend:',
'anomalies.title': 'Anomalous Transactions',
'anomalies.unknown': 'Unknown transaction',
'anomalies.unknownReason': 'Not specified',
'correlations.title': 'Category Correlations',
'summary.title': 'Quick Summary',
'summary.totalExpenses': 'Total Expenses',
'summary.totalIncome': 'Total Income',
'summary.transactionCount': 'Transactions Count',
'summary.expenseCount': 'Expense Transactions Count',
'summary.averageExpense': 'Average Expense per Transaction',
'insight.budget_exceed_forecast.title': '⚠️ Warning: Budget Exceed Forecast',
'insight.budget_exceed_forecast.desc': 'You are projected to spend {projected} DZD next month, exceeding your monthly budget ({budget} DZD) by {percent}%',
'insight.budget_exceed_forecast.action': 'Consider reducing unnecessary expenses',
'insight.budget_forecast.title': '📊 Monthly Expense Forecast',
'insight.budget_forecast.desc': 'You are projected to spend {projected} DZD next month, within your monthly budget ({budget} DZD)',
'insight.budget_forecast.action': 'Keep up the smart spending',
'insight.correlation_found.title': '🔗 Category Correlation',
'insight.correlation_found.desc': 'There is a {strength} {type} correlation between "{cat1}" and "{cat2}" (correlation coefficient: {corr})',
'insight.correlation_found.action': 'Monitor these two categories together to control spending',
'insight.anomaly_detected.title': '🚨 Unusual Expense',
'insight.anomaly_detected.desc': 'An unusual transaction was detected: "{desc}" for {amount} DZD ({reason})',
'insight.anomaly_detected.action': 'Verify this transaction',
'insight.goal_progress.title': '🎯 Saving Goal Progress',
'insight.goal_progress.desc': '{name}: {progress}% achieved, {remaining} DZD remaining',
'insight.goal_progress.action': 'You\'re close to achieving your goal! Keep going',
'insight.spending_behavior.title': '📈 Spending Pattern',
'insight.spending_behavior.desc': 'Most of your spending ({count} transactions) is {type} with an average of {avg} DZD, mostly in "{category}"',
'insight.spending_behavior.action': 'Review these transactions for saving opportunities',
'insight.saving_suggestion.title': '💡 Saving Suggestion',
'insight.saving_suggestion.desc': 'The category "{category}" accounts for {percent}% of your total expenses ({amount} DZD)',
'insight.saving_suggestion.action': 'Try reducing spending on "{category}" by 10% to save {savings} DZD per month',
        date: 'Date',
        overBudgetAlert: '⚠️ Warning: You have exceeded your monthly budget by {amount}!',
        overBudgetToast: '⚠️ Warning: After adding this transaction, you exceeded your monthly budget ({budget}) by {amount}',
        budgetWarning: '⚠️ Notice: Only {amount} left of your monthly budget.',
        budgetUpdated: '✅ Monthly budget updated successfully!',
        enterValidNumber: 'Please enter a valid number (>= 0)',
        budgetProgress: 'Monthly Budget',
budgetStatusSafe: '✅ Within budget',
budgetStatusWarning: '⚠️ Approaching limit',
budgetStatusDanger: '🚨 Budget exceeded!',
        defaultCategories: {
            Food: 'Food',
            Transport: 'Transport',
            Books: 'Books',
            Supplies: 'Supplies',
            Entertainment: 'Entertainment',
            Rent: 'Rent',
            Utilities: 'Utilities',
            Healthcare: 'Healthcare',
            Other: 'Other'
        }
    }
};

let currentLang = localStorage.getItem('lang') || 'ar';

function getLang() {
    return currentLang;
}

function setLang(lang) {
    if (translations[lang]) {
        currentLang = lang;
        localStorage.setItem('lang', lang);
        applyTranslations();
        // ===== إعادة تحميل التحليلات عند تغيير اللغة =====
        if (window.loadAnalytics && typeof window.loadAnalytics === 'function') {
            setTimeout(() => window.loadAnalytics(), 100);
        }
    }
}

function t(key, params = {}) {
    const langData = translations[currentLang];
    if (!langData) return key;
    const keys = key.split('.');
    let value = langData;
    for (let k of keys) {
        if (value && value[k] !== undefined) value = value[k];
        else return key;
    }
    if (typeof value === 'string' && params) {
        return value.replace(/\{(\w+)\}/g, (match, p1) => params[p1] || match);
    }
    return value;
}

// جعل الدوال متاحة في النطاق العام
window.t = t;
window.setLang = setLang;
window.currentLang = currentLang;

function applyTranslations() {
    // ترجمة النصوص الثابتة في الصفحة
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        el.textContent = t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        el.placeholder = t(key);
    });
    // ترجمة خيارات select
    document.querySelectorAll('select[data-i18n-options]').forEach(select => {
        const keyPrefix = select.getAttribute('data-i18n-options');
        const options = select.querySelectorAll('option');
        options.forEach(opt => {
            const val = opt.value;
            if (val) {
                const transKey = keyPrefix + '.' + val;
                opt.textContent = t(transKey);
            }
        });
    });
    // تحديث النص داخل عناصر أخرى (مثل التنبيهات)
    // سيتم التعامل معها داخل app.js
}
